spring:
  boot:
    admin:
      client:
        url: http://localhost:8081/
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: docker
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    protocol: smtp
    host: smtp.mailtrap.io
    port: 2525
    username: 1cc6c6b885ebe7
    password: e9729607a6fcb4
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

application:
  mail:
    late: Atenção você tem empréstimo(s) atrasado(s), por favor devolva o livro
    remetent: ederfmatos@gmail.com

management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  file:
    name: library-api.log
